application: offline-map
version: 20120330
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: site/index.html
  upload: site/index.html

- url: /
  static_dir: site/
